apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.frontend.name }}
    {{- include "interview-demo.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
