apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: interview-demo

resources:
  - namespace.yml
  - configmap.yml
  - backend-deployment.yml
  - backend-service.yml
  - frontend-deployment.yml
  - frontend-service.yml
  - ingress.yml

commonLabels:
  app.kubernetes.io/managed-by: gitlab-ci
  app.kubernetes.io/part-of: interview-demo
